import type { GaussianCloud } from './gaussian';

const encoder = new TextEncoder();

export function exportPly(cloud: GaussianCloud): Blob {
  const header = encoder.encode(`ply\nformat binary_little_endian 1.0\ncomment Generated by PoseSplat Studio\nelement vertex ${cloud.count}\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\nproperty float scale_0\nproperty float scale_1\nproperty float scale_2\nproperty float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\nproperty float opacity\nproperty float depth\nproperty float confidence\nend_header\n`);
  const stride = 56;
  const body = new ArrayBuffer(cloud.count * stride);
  const view = new DataView(body);
  for (let i = 0; i < cloud.count; i += 1) {
    let o = i * stride;
    for (let j = 0; j < 3; j += 1, o += 4) view.setFloat32(o, cloud.position[i * 3 + j], true);
    for (let j = 0; j < 4; j += 1, o += 1) view.setUint8(o, cloud.color[i * 4 + j]);
    for (let j = 0; j < 3; j += 1, o += 4) view.setFloat32(o, Math.log(Math.max(1e-7, cloud.scale[i * 3 + j])), true);
    for (let j = 0; j < 4; j += 1, o += 4) view.setFloat32(o, cloud.rotation[i * 4 + j], true);
    view.setFloat32(o, Math.log(cloud.opacity[i] / Math.max(1e-7, 1 - cloud.opacity[i])), true); o += 4;
    view.setFloat32(o, cloud.depth[i], true); o += 4;
    view.setFloat32(o, cloud.confidence[i], true);
  }
  return new Blob([header, body], { type: 'application/octet-stream' });
}

export function exportSplat(cloud: GaussianCloud): Blob {
  const buffer = new ArrayBuffer(cloud.count * 32);
  const view = new DataView(buffer);
  for (let i = 0; i < cloud.count; i += 1) {
    let o = i * 32;
    for (let j = 0; j < 3; j += 1, o += 4) view.setFloat32(o, cloud.position[i * 3 + j], true);
    for (let j = 0; j < 3; j += 1, o += 4) view.setFloat32(o, cloud.scale[i * 3 + j], true);
    for (let j = 0; j < 4; j += 1, o += 1) view.setUint8(o, cloud.color[i * 4 + j]);
    for (let j = 0; j < 4; j += 1, o += 1) view.setUint8(o, Math.round(cloud.rotation[i * 4 + j] * 128 + 128));
  }
  return new Blob([buffer], { type: 'application/octet-stream' });
}

export function download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url; link.download = filename; link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
