import type { GaussianCloud } from "./gaussian";
import { serializeSpz } from "spz-js";
const encoder = new TextEncoder(),
  SH_C0 = 0.28209479177387814;
const logit = (v: number) =>
  Math.log(
    Math.min(0.9999, Math.max(0.0001, v)) /
      (1 - Math.min(0.9999, Math.max(0.0001, v))),
  );
// Internal Three.js Y-up -> requested RDF output (+X right, -Y up, +Z front).
const outputPosition = (cloud: GaussianCloud, i: number) => [
  cloud.position[i * 3],
  -cloud.position[i * 3 + 1],
  cloud.position[i * 3 + 2],
];
const outputRotation = (cloud: GaussianCloud, i: number) => [
  -cloud.rotation[i * 4],
  cloud.rotation[i * 4 + 1],
  -cloud.rotation[i * 4 + 2],
  cloud.rotation[i * 4 + 3],
];

/** Graphdeco/SuperSplat binary PLY plus trailing debug properties. Every field is float for broad loader compatibility. */
export function exportPly(cloud: GaussianCloud): Blob {
  const names = [
    "x",
    "y",
    "z",
    "f_dc_0",
    "f_dc_1",
    "f_dc_2",
    "opacity",
    "scale_0",
    "scale_1",
    "scale_2",
    "rot_0",
    "rot_1",
    "rot_2",
    "rot_3",
    "depth",
    "confidence",
    "source_layer",
  ];
  const header = encoder.encode(
      `ply\nformat binary_little_endian 1.0\ncomment Generated by PoseSplat Studio\ncomment coordinate RDF +X right -Y up +Z front\nelement vertex ${cloud.count}\n${names.map((n) => `property float ${n}`).join("\n")}\nend_header\n`,
    ),
    body = new ArrayBuffer(cloud.count * names.length * 4),
    view = new DataView(body);
  for (let i = 0; i < cloud.count; i++) {
    const q = outputRotation(cloud, i),
      values = [
        ...outputPosition(cloud, i),
        ...Array.from(
          cloud.color.subarray(i * 4, i * 4 + 3),
          (v) => (v / 255 - 0.5) / SH_C0,
        ),
        logit(cloud.opacity[i]),
        ...Array.from(cloud.scale.subarray(i * 3, i * 3 + 3), Math.log),
        q[3],
        q[0],
        q[1],
        q[2],
        cloud.depth[i],
        cloud.confidence[i],
        cloud.layer[i],
      ];
    values.forEach((v, j) =>
      view.setFloat32((i * names.length + j) * 4, v, true),
    );
  }
  return new Blob([header, body], { type: "application/octet-stream" });
}
export function exportSplat(cloud: GaussianCloud): Blob {
  const buffer = new ArrayBuffer(cloud.count * 32),
    view = new DataView(buffer);
  for (let i = 0; i < cloud.count; i++) {
    let o = i * 32;
    for (const v of outputPosition(cloud, i)) {
      view.setFloat32(o, v, true);
      o += 4;
    }
    for (let j = 0; j < 3; j++, o += 4)
      view.setFloat32(o, cloud.scale[i * 3 + j], true);
    for (let j = 0; j < 4; j++, o++) view.setUint8(o, cloud.color[i * 4 + j]);
    for (const v of outputRotation(cloud, i))
      view.setUint8(o++, Math.round(v * 128 + 128));
  }
  return new Blob([buffer], { type: "application/octet-stream" });
}
export async function exportSpz(cloud: GaussianCloud): Promise<Blob> {
  const positions = new Float32Array(cloud.count * 3),
    rotations = new Float32Array(cloud.count * 4),
    colors = new Float32Array(cloud.count * 3),
    scales = new Float32Array(cloud.count * 3),
    alphas = new Float32Array(cloud.count);
  for (let i = 0; i < cloud.count; i++) {
    positions.set(outputPosition(cloud, i), i * 3);
    rotations.set(outputRotation(cloud, i), i * 4);
    for (let j = 0; j < 3; j++) {
      colors[i * 3 + j] = (cloud.color[i * 4 + j] / 255 - 0.5) / 0.15;
      scales[i * 3 + j] = Math.log(Math.max(1e-7, cloud.scale[i * 3 + j]));
    }
    alphas[i] = logit(cloud.opacity[i]);
  }
  const bytes = await serializeSpz({
    numPoints: cloud.count,
    shDegree: 0,
    antialiased: true,
    positions,
    scales,
    rotations,
    alphas,
    colors,
    sh: new Float32Array(0),
  });
  return new Blob([bytes.buffer as ArrayBuffer], {
    type: "application/octet-stream",
  });
}
export function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob),
    link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
